language: node_js
sudo: false
node_js:
    - 7
services:
  - mysql

cache:
    yarn: true
    directories:
        - node_modules

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS flux;'

script:
    # Try to build and start
    - yarn test
deploy:
    - provider: script
      skip_cleanup: true
      script: "./deploy.sh"
      on:
          all_branches: true
